import { type AppType } from "next/app";
import Layout from "~/pages/layout";
import { Theme } from "@radix-ui/themes";
import Head from "next/head";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary-radial absolute inset-0 h-full w-full">
        <Theme>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </Theme>
      </div>
    </>
  );
};

export default MyApp;
